import type { MetricDefinition } from '../types';

export const METRICS: MetricDefinition[] = [
  {
    key: 'marketCap',
    label: 'Market Cap',
    tooltip: 'Total dollar market value of a company\'s outstanding shares of stock.',
    format: 'currency'
  },
  {
    key: 'earnings',
    label: 'Earnings',
    tooltip: 'Net income generated by the company over the trailing 12 months (TTM).',
    format: 'currency'
  },
  {
    key: 'revenue',
    label: 'Revenue',
    tooltip: 'Total amount of income generated by the sale of goods or services (TTM).',
    format: 'currency'
  },
  {
    key: 'employees',
    label: 'Employees',
    tooltip: 'Total number of full-time worldwide employees.',
    format: 'number'
  },
  {
    key: 'peRatio',
    label: 'P/E Ratio',
    tooltip: 'Price-to-Earnings ratio. Ratio of share price to earnings per share.',
    format: 'ratio'
  },
  {
    key: 'dividendYield',
    label: 'Dividend %',
    tooltip: 'Annual dividend payment per share divided by current share price.',
    format: 'percent'
  },
  {
    key: 'operatingMargin',
    label: 'Op. Margin',
    tooltip: 'Operating income divided by revenue, measuring profitability from core operations.',
    format: 'percent'
  },
  {
    key: 'totalAssets',
    label: 'Total Assets',
    tooltip: 'Total economic resources owned by the company recorded on the balance sheet.',
    format: 'currency'
  },
  {
    key: 'netAssets',
    label: 'Net Assets',
    tooltip: 'Total assets minus total liabilities (Stockholders\' Equity).',
    format: 'currency'
  },
  {
    key: 'totalLiabilities',
    label: 'Total Liabilities',
    tooltip: 'Total financial debts and obligations owed to outside parties.',
    format: 'currency'
  },
  {
    key: 'totalDebt',
    label: 'Total Debt',
    tooltip: 'Sum of short-term and long-term interest-bearing debt obligations.',
    format: 'currency'
  },
  {
    key: 'cashOnHand',
    label: 'Cash on Hand',
    tooltip: 'Cash and short-term liquid investments available for immediate use.',
    format: 'currency'
  },
  {
    key: 'priceToBook',
    label: 'P/B Ratio',
    tooltip: 'Price-to-Book ratio. Ratio of market value to balance sheet book value.',
    format: 'ratio'
  },
  {
    key: 'costToBorrow',
    label: 'Cost to Borrow',
    tooltip: 'Annualized fee percentage charged by lenders to borrow shares for shorting.',
    format: 'percent'
  }
];
